### ISSUE TITLE
3x6 version

### ISSUE THREAD

**Issue by EnotionZ** [HID-Technologies/Skeleton-Dactyl-Mini#17]
Can you create a version with 6 columns? I'm building the Charybdis 3x6 mini and would love a matching one w/o the trackball on the other side.

**Comment by EnotionZ** [comment]
Or if you provide the f3d file for the Charybdis 3x6, I'd appreciate that even more.

**Comment by bstiq** [comment]
Hello !

Please check out the TBK Mini: https://github.com/Bastardkb/TBK-Mini

At this moment I have no plans to open source the f3d files for the Charybdis.

Regards,
