### ISSUE TITLE
Heat set insert clarification

### ISSUE THREAD

**Issue by matthews-jca** [HID-Technologies/Skeleton-Dactyl-Mini#21]
Build list mentions "M4 screw insert, M4 X D6.0 X L5.0" but the link supplied shows 4mm length. Also measuring the supports in the printed case show them to be 4mm length as well. Should these be 4mm or 5mm long?

**Comment by bstiq** [comment]
Hello,

The page automatically selects the L4, there is no way to add a link that selects the required L5.
For the builds, we use and recommend L5, though L4 might work
