### ISSUE TITLE
Spatial dimensions?

### ISSUE THREAD

**Issue by ferrosa** [HID-Technologies/Skeleton-Dactyl-Mini#23]
Could you please provide the spatial dimensions of the finished build (keycaps on)?

Reason: I have a below-table keyboard slot of 11cm height, which is perfect for my conventional keyboard (Cherry peaking at ~4.5cm), but might be tight with a Skeletyl (+ fingers). It's arguably simpler for you to measure it than for me to test print a mockup just for height fitting. Also, I'm not holding out any hope for tenting.

**Comment by bstiq** [comment]
Hey, 

I measure around 5.5cm with DES keycaps and no tents.
With hands, it seems to fit under 10cm.

**Comment by ferrosa** [comment]
Thanks for the info! Looking good, will order a kit from your website soon.
Also impressive response time.
