### ISSUE TITLE
Compatibility with a regular pro micro

### ISSUE THREAD

**Issue by heyitscassio** [HID-Technologies/Skeleton-Dactyl-Mini#3]
In the parts list it says that a elite c is needed to build this keyboard, but a regular arduino pro micro would work? Without any modifications or light modifications? If any modification is needed, how one would make those modifications?

Thanks.

**Comment by bstiq** [comment]
Hello,

Thank you for getting in touch !
The case model is indeed made for elite-Cs - the hole in the case is he
size of USB-C.
I reckon a pro micro should work though !

Regards,

*Quentin LEBASTARD*


Le sam. 26 juin 2021 à 05:48, Cássio Ávila ***@***.***> a
écrit :

**Comment by heyitscassio** [comment]
How one would go about remodeling the hole to fit exactly a regular pro mico? Sorry I know nothing about 3D modeling.

**Comment by bstiq** [comment]
Hey sorry didn't see your reply.
If you don't know anything about fusion modeling, it's going to be difficult.

I've seen a few people using a pro micro with hotglue, so it should be no problem !

Regards,
