### ISSUE TITLE
Question on mounting the Elite-C using the 3D-printed shield adapter

### ISSUE THREAD

**Issue by cyanindya** [HID-Technologies/Skeleton-Dactyl-Mini#4]
Hello, first, thank you for designing this awesome keyboard! I'm about to start building it and decided to go for handwired approach since it is difficult to get flexible PCB here, and while I mostly get the gist of the building process so far, there is something that still lost to me. Specifically, regarding use of printable shield adapter from Geoff, since I am still unfamiliar with 3D printing in general.

This may seem mundane, but with the 3D-printed adapter, how am I supposed to mount the Elite-C to it? In the Dometyl repository, it is stated that I can solder around or glue the components to it, but I am still a bit lost about the exact process. Say that if I am to use solder to "lock" the Elite-C to the adapter, since it is 3D-printed, will it be possible for the process to accidentally melt the adapter and mess up both the printed adapter and the Elite-C? Or if the glue approach is better, what kind of glue that is safe to use, and at which spots should they be applied to?

With the use of the adapter PCB, I understand perfectly well the process (i.e. the soldering), but it is difficult to find local PCB manufacturer in my place that can print using 1mm PCB, hence why I'm considering to go for the printable shield adapter instead.

Thank you!

**Comment by geoffder** [comment]
Hey there, I hope that these [pictures of a recent build of mine](https://github.com/geoffder/dometyl-keyboard/tree/main/things/boards/niztyl) can be of some help. When I said "solder around" I was suggesting that you might use headers, then solder on to the other side, or plug connectors on to the pins. What I found worked for me was soldering on some select headers, and using those to line up the MCU for hot gluing over the holes. Then I just soldered into the pinholes on the side facing out. 

Now that there are those build images (which didn't exist when I first added those notes, it may be time to revise it and add a link.

**Comment by cyanindya** [comment]
It's clear enough so far, thank you - it makes sense now! May I ask what specific glue that you used, or similar ones those should be safe?

**Comment by geoffder** [comment]
I just used the glue that came with [this gun](https://www.amazon.ca/Chanseon-Industrial-Adjustable-Temperature-Nozzles/dp/B08PPC5VTR/ref=sr_1_1?keywords=chanseon+glue&qid=1637025618&sr=8-1). I'm sure most hot glue sticks will be safe / strong enough for this use case though.

**Comment by cyanindya** [comment]
That should be clear enough - thank you! Then I'll close the inquiry for now.
