### ISSUE TITLE
Blackpill Build details

### ISSUE THREAD

**Issue by camrbuss** [HID-Technologies/Skeleton-Dactyl-Mini#6]
What is the difference between the blackpill case and the normal case?

Will an adapter board be created for the blackpill?

What are the suggested print settings for the organic tent? Does it require support material?

Love this keyboard! Thanks for open-sourcing all the hard work of your designs.

**Comment by bstiq** [comment]
Hello,

The blackpill case is made to work with the blackpill shield available here: 
https://github.com/Bastardkb/adapter-blackpill/
It's a work in progress though - we confirmed hardware and firmware work for the Charybdis Nano, but we're still working on adding features (look at the issues of the repo if you want a better idea).

For the organic tents you should add supports everywhere (not only on the bed).

Thank you for the kind words ! I'm glad you like the keyboard.
On a sidenote, I just ordered the flexible PCBs with per-key RGB for the skeletyl, if you want to order those as well :)

Regards,
