### ISSUE TITLE
Possibility of adding case variant for hotswappable mcu

### ISSUE THREAD

**Issue by karrui** [HID-Technologies/Skeleton-Dactyl-Mini#7]
Thanks for open sourcing the case! As the mcu hotswap spacers are slightly taller than their non hotswap variant, the USB-C cutouts do not line up correctly when used with a hotswapped mcu. 

Is it possible to request for a case variant with repositioned USB-C cutout to fit a hotswapped mcu?

**Comment by bstiq** [comment]
Hello,

I recommend using either millmax sockets,
Or using the rev2 shield PCB where you can hotswap the ribbon cables (https://github.com/Bastardkb/Elite-C-holder/pull/1)

I can also provide you with a step file if you want to change the alignment yourself.

Let me know if that works for you.

**Comment by karrui** [comment]
> I recommend using either millmax sockets,

I'm using the hotswap sockets from [kriscables](https://kriscables.com/product/mill-max-low-profile-sockets/), which are slightly higher than the default spacer height. Are there shorter sockets I am not aware of? :(

Ah, neglected to also mention that I am already using the rev2 shield PCB! Is there an image of how to the hotswapping of ribbon cables are done?

I am not familiar with editing the step file at all, but am willing to try if a step file is provided! :)

**Comment by karrui** [comment]
Would [these sockets](https://keeb.io/products/peel-a-way-sockets-for-pro-micros) work better?

**Comment by karrui** [comment]
Or [these](https://splitkb.com/products/mill-max-low-profile-sockets?pr_prod_strat=copurchase&pr_rec_id=9404945f5&pr_rec_pid=4161982758989&pr_ref_pid=4786687737933&pr_seq=uniform)? Seem much lower actually!

**Comment by bstiq** [comment]
Hey,
I don't think the peelaway should work.
I recommend using the millmax on the matrix headers.
That way I have multiple shields each with a different MCU, and I just have to disconnect the cables when I want to switch.

Maybe this picture makes it clearer?
![image](https://user-images.githubusercontent.com/1847115/163354507-a3c0b991-2139-43b1-b479-0810d3d46aed.png)

Regards,

**Comment by karrui** [comment]
Ah, you solder the mcu and allow the breakout pcb to be hotswapped instead. I was planning to make the entire mcu hotswappable ala https://docs.splitkb.com/hc/en-us/articles/360011263059-How-do-I-socket-a-microcontroller-

However, at this point I'm about to just socket the mcu directly instead of going through all that trouble, haha!

**Comment by bstiq** [comment]
Hello,

This is correct.
Since it seems you are going ahead with the build I am closing this issue, have fun !

Regards,

**Comment by karrui** [comment]
Oops, I should have closed it myself.

For others who stumble onto this issue in the future, millmax 315 sockets ([these, to be exact](https://www.digikey.sg/en/products/detail/mill-max-manufacturing-corp/315-93-112-41-003000/4455358)) are the exact height as the default header pins that come with nice!nano and works perfectly. millmax 310 sockets (the higher profile variant) will not work.

PS: millmax 315/310 sockets work perfectly to also hotswap the ribbon cable.
